settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 1323
  host: localhost
schema:
  - name: echoSample
    path: .
    commands: {}
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore:
        paths:
          - .git
          - .realize
          - vendor
